config/routes.rb
TwitterLists::Application.routes.draw do
  root to: "twitter_lists#new"

  resources :twitter_lists, only: [:new, :create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/twitter_lists_controller.rb
class TwitterListsController < ApplicationController
  def new
  end

  def create
    if params[:password] == "hacksonhacksonhacks"
      Twitter.list_add_member('the-hacker-league', params[:handle])
      flash[:message] = "Success. Probably. Check yo twitter"
    else
      flash[:error] = "Hacks. Wrong password"
    end
    render :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_lists_helper.rb
module TwitterListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterLists</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <%= msg %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/twitter_lists/new.html.erb
<%= form_tag twitter_lists_path, method: "post" do %>
  <%= label_tag(:handle, "@") %>
  <%= text_field_tag(:handle) %>
  <%= label_tag(:password, "Password") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Add yourself to the list") %>
 <% end %>